#!/usr/bin/env python3
"""
Compare MP and VASP energies from MP phase relaxation workflow.

Compares:
- MP GGA-PBE DFT energies (from mp_vaspdft.json, generated by get_mp_struct.py or compute_dft_e_hull.py)
- VASP PBE DFT energies (from local VASP relaxation calculations)

Note: 
- No longer queries MP API directly (loads from JSON file)
- Ensures consistent energy source (same as used for structure download)
- Faster and more reproducible
"""

import os
import json
import argparse
import numpy as np
from pathlib import Path
from collections import defaultdict

from pymatgen.io.vasp.outputs import Vasprun
import matplotlib.pyplot as plt
import matplotlib as mpl

# Use non-interactive backend for cluster
mpl.use('Agg')


def load_workflow_db(db_path):
    """Load workflow database."""
    with open(db_path, 'r') as f:
        return json.load(f)


def load_mp_energies_from_json(json_path):
    """
    Load MP GGA-PBE DFT energies from JSON file.
    
    Expected to be generated by:
    - get_mp_struct.py (saves to mp_cache_structs/mp_vaspdft.json)
    - compute_dft_e_hull.py (saves to VASP_JOBS/mp_vaspdft.json)
    
    JSON format:
    [
        {
            "mp_id": "mp-12345",
            "entry_id": "mp-12345-GGA",
            "energy_per_atom": -5.12345,
            "chemsys": "Li-N",
            ...
        },
        ...
    ]
    
    Args:
        json_path: Path to mp_vaspdft.json file
    
    Returns:
        dict: {mp_id: energy_per_atom} using GGA-PBE functional
    """
    json_path = Path(json_path)
    
    if not json_path.exists():
        raise FileNotFoundError(
            f"MP energies file not found: {json_path}\n"
            f"Please generate it by running:\n"
            f"  1. get_mp_struct.py (saves to mp_cache_structs/mp_vaspdft.json), or\n"
            f"  2. compute_dft_e_hull.py (saves to VASP_JOBS/mp_vaspdft.json)"
        )
    
    print(f"\nLoading MP GGA-PBE DFT energies from: {json_path}")
    
    with open(json_path, 'r') as f:
        mp_data = json.load(f)
    
    mp_energies = {}
    for entry in mp_data:
        mp_id = entry.get('mp_id')
        energy_per_atom = entry.get('energy_per_atom')
        
        if mp_id and energy_per_atom is not None:
            mp_energies[mp_id] = float(energy_per_atom)
    
    print(f"  Loaded {len(mp_energies)} MP GGA-PBE energies (uncorrected, raw DFT)\n")
    
    return mp_energies


def check_electronic_convergence_oszicar(relax_dir):
    """
    Check electronic convergence from OSZICAR and return energy.

    Searches backwards through ionic steps (F= lines) to find the most recent
    one with converged electronic SCF (iteration count < NELM). Returns the
    energy from that step for reliable timeout recovery.

    Args:
        relax_dir: Path to VASP relaxation directory (contains OSZICAR and INCAR)

    Returns:
        tuple: (converged: bool, total_energy: float or None)
    """
    relax_dir = Path(relax_dir)
    oszicar_path = relax_dir / 'OSZICAR'
    incar_path = relax_dir / 'INCAR'

    if not oszicar_path.exists():
        return False, None

    nelm = 60
    if incar_path.exists():
        try:
            with open(incar_path, 'r') as f:
                for line in f:
                    if 'NELM' in line and '=' in line:
                        val = line.split('=')[1].split()[0].strip()
                        nelm = int(val)
                        break
        except Exception:
            pass

    try:
        with open(oszicar_path, 'r') as f:
            lines = [l.rstrip() for l in f.readlines() if l.strip()]

        if len(lines) < 2:
            return False, None

        search_from = len(lines) - 1
        while search_from > 0:
            f_idx = None
            for i in range(search_from, -1, -1):
                if 'F=' in lines[i]:
                    f_idx = i
                    break

            if f_idx is None or f_idx < 1:
                return False, None

            f_line = lines[f_idx]
            try:
                f_pos = f_line.index('F=')
                energy_str = f_line[f_pos + 2:].split()[0]
                total_energy = float(energy_str)
            except (ValueError, IndexError):
                search_from = f_idx - 1
                continue

            scf_line = lines[f_idx - 1]
            parts = scf_line.split()
            if len(parts) >= 2:
                try:
                    e_step = int(parts[1])
                    if e_step < nelm:
                        return True, total_energy
                except ValueError:
                    pass

            search_from = f_idx - 1

        return False, None

    except Exception:
        return False, None


def check_vasp_convergence(relax_dir):
    """
    Check if VASP calculation truly converged by reading vasprun.xml.
    Falls back to OSZICAR if vasprun.xml is incomplete (timeout case).
    
    Args:
        relax_dir: Path to VASP relaxation directory
    
    Returns:
        bool: True if converged, False otherwise
    """
    relax_dir = Path(relax_dir)
    vasprun_path = relax_dir / 'vasprun.xml'
    
    # Try vasprun.xml first (standard case)
    if vasprun_path.exists():
        try:
            vr = Vasprun(str(vasprun_path), parse_dos=False, parse_eigen=False)
            return vr.converged_electronic
        except Exception:
            # vasprun.xml exists but corrupted - likely timeout
            pass
    
    # Fall back to OSZICAR (timeout case)
    converged, _ = check_electronic_convergence_oszicar(relax_dir)
    return converged


def analyze_energy_differences(db, mp_energies, check_convergence=True, outlier_threshold=0.5):
    """
    Analyze energy differences between MP (uncorrected DFT) and VASP.
    
    Args:
        db: Workflow database
        mp_energies: dict of {mp_id: energy_per_atom} from MP API
        check_convergence: If True, verify VASP convergence and exclude non-converged
        outlier_threshold: Energy difference threshold (eV/atom) for outlier detection
    
    Returns:
        dict: Statistics and structure lists
    """
    completed = {}
    skipped_not_converged = []
    skipped_no_energy = []
    recovered_from_outcar = []
    
    for mp_id, sdata in db['structures'].items():
        if sdata['state'] not in ('RELAX_DONE', 'RELAX_TMOUT'):
            continue
        
        # Get VASP energy - try from database first, fall back to OUTCAR if None
        vasp_energy_per_atom = sdata.get('vasp_energy_per_atom')
        
        if vasp_energy_per_atom is None and sdata.get('relax_dir'):
            relax_dir = Path(sdata['relax_dir'])
            contcar_path = relax_dir / 'CONTCAR'
            
            if contcar_path.exists():
                try:
                    from pymatgen.core import Structure
                    
                    converged, total_energy = check_electronic_convergence_oszicar(relax_dir)
                    if converged and total_energy is not None:
                        structure = Structure.from_file(str(contcar_path))
                        n_atoms = len(structure)
                        vasp_energy_per_atom = total_energy / n_atoms
                        sdata['vasp_energy_per_atom'] = vasp_energy_per_atom
                        recovered_from_outcar.append(mp_id)
                        print(f"  INFO: Recovered {mp_id} energy from OSZICAR (timed out)")
                except Exception as e:
                    print(f"  WARNING: Could not extract {mp_id} energy from OSZICAR: {e}")
        
        if vasp_energy_per_atom is None:
            skipped_no_energy.append(mp_id)
            continue
        
        # Get MP energy from fetched energies
        mp_e = mp_energies.get(mp_id)
        
        if mp_e is None:
            continue
        
        # Check VASP convergence (skip for RELAX_TMOUT -- already validated by workflow)
        if check_convergence and sdata['state'] != 'RELAX_TMOUT' and sdata.get('relax_dir'):
            if not check_vasp_convergence(sdata['relax_dir']):
                skipped_not_converged.append(mp_id)
                print(f"  WARNING: Skipping {mp_id} - VASP calculation not converged")
                continue

        sdata['mp_energy_per_atom'] = mp_e
        completed[mp_id] = sdata
    
    if not completed:
        return None
    
    # Report filtering results
    if recovered_from_outcar:
        print(f"\n  Recovered {len(recovered_from_outcar)} energies from OUTCAR (timed-out jobs)")
    if skipped_no_energy:
        print(f"  Skipped {len(skipped_no_energy)} structures (no VASP energy available)")
    if skipped_not_converged:
        print(f"  Filtered out {len(skipped_not_converged)} non-converged structures")
    
    # First pass: calculate all differences to detect outliers
    all_diffs = []
    for mp_id, sdata in completed.items():
        mp_e = sdata['mp_energy_per_atom']
        vasp_e = sdata['vasp_energy_per_atom']
        diff = vasp_e - mp_e
        all_diffs.append((mp_id, diff, abs(diff), sdata))
    
    # Detect statistical outliers using IQR method
    abs_diffs = [abs_diff for _, _, abs_diff, _ in all_diffs]
    q25, q75 = np.percentile(abs_diffs, [25, 75])
    iqr = q75 - q25
    outlier_threshold_iqr = q75 + 3 * iqr
    outlier_threshold_abs = outlier_threshold
    
    # Build structures list with is_outlier flag
    diffs = []
    by_chemsys = defaultdict(list)
    n_outliers = 0
    
    for mp_id, diff, abs_diff, sdata in all_diffs:
        is_outlier = abs_diff > outlier_threshold_iqr or abs_diff > outlier_threshold_abs
        diffs.append({
            'mp_id': mp_id,
            'chemsys': sdata['chemsys'],
            'formula': sdata['formula'],
            'mp_energy': sdata['mp_energy_per_atom'],
            'vasp_energy': sdata['vasp_energy_per_atom'],
            'diff': diff,
            'abs_diff': abs_diff,
            'is_outlier': is_outlier,
        })
        if is_outlier:
            n_outliers += 1
            print(f"  WARNING: Excluding outlier {mp_id} ({sdata['formula']}): "
                  f"Δ = {diff:+.4f} eV/atom (|Δ| = {abs_diff:.4f})")
        else:
            by_chemsys[sdata['chemsys']].append(diff)
    
    if n_outliers:
        print(f"\n  Flagged {n_outliers} statistical outliers "
              f"(|Δ| > {outlier_threshold:.2f} eV/atom or > Q3+3*IQR)")
    
    n_non_outlier = len(diffs) - n_outliers
    print(f"  Analyzing {n_non_outlier} structures after filtering\n")
    
    # Statistics on non-outliers only
    non_outlier = [d for d in diffs if not d['is_outlier']]
    diff_values = [d['diff'] for d in non_outlier]
    abs_diff_values = [d['abs_diff'] for d in non_outlier]
    
    stats = {
        'n_structures': n_non_outlier,
        'n_total': len(diffs),
        'n_recovered_from_outcar': len(recovered_from_outcar),
        'n_skipped_no_energy': len(skipped_no_energy),
        'n_skipped_not_converged': len(skipped_not_converged),
        'n_outliers': n_outliers,
        'outlier_threshold': outlier_threshold,
        'outlier_threshold_iqr': round(float(outlier_threshold_iqr), 6),
        'mean_diff': np.mean(diff_values),
        'std_diff': np.std(diff_values),
        'mae': np.mean(abs_diff_values),
        'rmse': np.sqrt(np.mean([d**2 for d in diff_values])),
        'min_diff': np.min(diff_values),
        'max_diff': np.max(diff_values),
        'median_diff': np.median(diff_values),
        'q25': np.percentile(diff_values, 25),
        'q75': np.percentile(diff_values, 75)
    }
    
    # Per-chemsys statistics (non-outliers only)
    chemsys_stats = {}
    for chemsys, chemsys_diffs in by_chemsys.items():
        chemsys_stats[chemsys] = {
            'n': len(chemsys_diffs),
            'mean': np.mean(chemsys_diffs),
            'std': np.std(chemsys_diffs),
            'mae': np.mean([abs(d) for d in chemsys_diffs]),
            'max_abs': max([abs(d) for d in chemsys_diffs])
        }
    
    return {
        'stats': stats,
        'chemsys_stats': chemsys_stats,
        'structures': diffs,
        'recovered_from_outcar': recovered_from_outcar,
        'skipped_no_energy': skipped_no_energy,
        'skipped_not_converged': skipped_not_converged,
    }


def plot_energy_comparison(results, output_prefix='mp_vasp_comparison'):
    """Create scatter and residual plots comparing MP vs VASP energies.

    Outliers (is_outlier=True) are plotted in a distinct color.
    Statistics in the legend box are computed on non-outlier points only.
    """
    structures = results['structures']
    stats = results['stats']

    normal = [s for s in structures if not s['is_outlier']]
    outliers = [s for s in structures if s['is_outlier']]

    vasp_n = np.array([s['vasp_energy'] for s in normal])
    mp_n = np.array([s['mp_energy'] for s in normal])
    vasp_o = np.array([s['vasp_energy'] for s in outliers]) if outliers else np.array([])
    mp_o = np.array([s['mp_energy'] for s in outliers]) if outliers else np.array([])

    all_vasp = np.concatenate([vasp_n, vasp_o]) if len(vasp_o) else vasp_n
    all_mp = np.concatenate([mp_n, mp_o]) if len(mp_o) else mp_n
    all_e = np.concatenate([all_vasp, all_mp])
    margin = (all_e.max() - all_e.min()) * 0.05
    plot_min, plot_max = all_e.min() - margin, all_e.max() + margin

    # --- Scatter plot ---
    fig, ax = plt.subplots(figsize=(12, 10))

    ax.scatter(vasp_n, mp_n, alpha=0.6, s=50, c='steelblue',
               edgecolors='black', linewidth=0.5,
               label=f'Non-outlier (N={len(normal)})', zorder=3)
    if len(vasp_o):
        ax.scatter(vasp_o, mp_o, alpha=0.7, s=50, c='#d62728', marker='x',
                   linewidth=1.2, label=f'Outlier (N={len(outliers)})', zorder=4)

    ax.plot([plot_min, plot_max], [plot_min, plot_max], 'r--', linewidth=2,
            alpha=0.7, label='Perfect agreement (y=x)')
    ax.fill_between([plot_min, plot_max],
                    [plot_min - 0.05, plot_max - 0.05],
                    [plot_min + 0.05, plot_max + 0.05],
                    alpha=0.2, color='green', label='±0.05 eV/atom')

    ax.set_xlabel('VASP PBE Energy per Atom (eV)', fontsize=12, fontweight='bold')
    ax.set_ylabel('MP GGA-PBE Energy per Atom (eV)', fontsize=12, fontweight='bold')
    ax.set_title(f'MP vs VASP DFT Energy Comparison\n'
                 f'(Pure GGA-PBE, N={stats["n_structures"]}, '
                 f'{stats["n_outliers"]} outliers)',
                 fontsize=14, fontweight='bold')

    stats_text = (
        f"N = {stats['n_structures']} (excl. outliers)\n"
        f"MAE = {stats['mae']:.4f} eV/atom\n"
        f"RMSE = {stats['rmse']:.4f} eV/atom\n"
        f"Mean Diff = {stats['mean_diff']:+.4f} eV/atom\n"
        f"Std Diff = {stats['std_diff']:.4f} eV/atom"
    )
    ax.text(0.05, 0.95, stats_text, transform=ax.transAxes, fontsize=10,
            verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

    ax.grid(True, alpha=0.3, linestyle='--')
    ax.minorticks_on()
    ax.grid(True, which='minor', alpha=0.15, linestyle=':')
    ax.legend(loc='lower right', fontsize=10)
    ax.set_aspect('equal', adjustable='box')
    ax.set_xlim(plot_min, plot_max)
    ax.set_ylim(plot_min, plot_max)

    plt.tight_layout()
    plot_file = f"{output_prefix}_scatter.png"
    plt.savefig(plot_file, dpi=300, bbox_inches='tight')
    print(f"\nScatter plot saved to: {plot_file}")
    plt.close()

    # --- Residual plot ---
    fig, ax = plt.subplots(figsize=(12, 10))

    res_n = vasp_n - mp_n
    ax.scatter(vasp_n, res_n, alpha=0.6, s=50, c='steelblue',
               edgecolors='black', linewidth=0.5,
               label=f'Non-outlier (N={len(normal)})', zorder=3)
    if len(vasp_o):
        res_o = vasp_o - mp_o
        ax.scatter(vasp_o, res_o, alpha=0.7, s=50, c='#d62728', marker='x',
                   linewidth=1.2, label=f'Outlier (N={len(outliers)})', zorder=4)
    else:
        res_o = np.array([])

    ax.axhline(y=0, color='r', linestyle='--', linewidth=2, alpha=0.7,
               label='Zero residual')
    ax.axhline(y=0.05, color='green', linestyle=':', linewidth=1.5, alpha=0.6,
               label='±0.05 eV/atom')
    ax.axhline(y=-0.05, color='green', linestyle=':', linewidth=1.5, alpha=0.6)
    ax.axhline(y=stats['mean_diff'], color='orange', linestyle='-', linewidth=2,
               alpha=0.7, label=f'Mean = {stats["mean_diff"]:+.4f} eV/atom')

    ax.set_xlabel('VASP PBE Energy per Atom (eV)', fontsize=12, fontweight='bold')
    ax.set_ylabel('Residual (VASP - MP) (eV/atom)', fontsize=12, fontweight='bold')
    ax.set_title(f'Energy Residuals vs VASP Energy\n'
                 f'(Pure GGA-PBE, N={stats["n_structures"]}, '
                 f'{stats["n_outliers"]} outliers)',
                 fontsize=14, fontweight='bold')

    all_res = np.concatenate([res_n, res_o]) if len(res_o) else res_n
    y_limit = max(0.15, np.max(np.abs(all_res)) * 1.2)
    ax.set_ylim(-y_limit, y_limit)

    ax.grid(True, alpha=0.3, linestyle='--')
    ax.minorticks_on()
    ax.grid(True, which='minor', alpha=0.15, linestyle=':')
    ax.legend(loc='best', fontsize=10)

    plt.tight_layout()
    residual_file = f"{output_prefix}_residuals.png"
    plt.savefig(residual_file, dpi=300, bbox_inches='tight')
    print(f"Residual plot saved to: {residual_file}")
    plt.close()


def print_summary(results):
    """Print minimal analysis summary."""
    stats = results['stats']
    
    print("\n" + "="*70)
    print("MP vs VASP Energy Comparison (Pure GGA-PBE Functional)")
    print("="*70)
    print(f"Structures analyzed: {stats['n_structures']}")
    if stats.get('n_recovered_from_outcar', 0) > 0:
        print(f"Recovered from OUTCAR (timed out): {stats['n_recovered_from_outcar']}")
    if stats.get('n_skipped_no_energy', 0) > 0:
        print(f"Skipped (no energy): {stats['n_skipped_no_energy']}")
    if stats.get('n_skipped_not_converged', 0) > 0:
        print(f"Skipped (not converged): {stats['n_skipped_not_converged']}")
    if stats.get('n_outliers', 0) > 0:
        print(f"Outliers (flagged): {stats['n_outliers']}")
    print(f"MAE:  {stats['mae']:.4f} eV/atom")
    print(f"RMSE: {stats['rmse']:.4f} eV/atom")
    print(f"Mean: {stats['mean_diff']:+.4f} eV/atom")
    print("="*70)


def save_detailed_comparison(results, output_file, mp_energies_file):
    """Save detailed comparison to JSON file."""
    # Add metadata about functional filtering, convergence checking, and outlier removal
    results['metadata'] = {
        'functional': 'GGA-PBE',
        'note': 'MP energies loaded from JSON file (generated by get_mp_struct.py or compute_dft_e_hull.py)',
        'mp_energies_source': str(mp_energies_file),
        'mp_field_used': 'energy_per_atom (uncorrected GGA-PBE energy, raw DFT)',
        'convergence_check': 'Only converged VASP calculations included (checks vasprun.xml, falls back to OUTCAR for timeouts)',
        'timeout_handling': 'Timed-out jobs with electronic convergence recovered from OUTCAR',
        'outlier_detection': 'Statistical outliers flagged (is_outlier field) using IQR method and absolute threshold',
        'outlier_threshold': results['stats'].get('outlier_threshold', 0.5),
        'outlier_threshold_iqr': results['stats'].get('outlier_threshold_iqr'),
        'n_recovered_from_outcar': results['stats'].get('n_recovered_from_outcar', 0),
        'n_skipped_no_energy': results['stats'].get('n_skipped_no_energy', 0),
        'n_skipped_not_converged': results['stats'].get('n_skipped_not_converged', 0),
        'n_outliers': results['stats'].get('n_outliers', 0)
    }
    
    with open(output_file, 'w') as f:
        json.dump(results, f, indent=2)
    
    print(f"\nDetailed results saved to: {output_file}")
    print(f"  (MP GGA-PBE from {mp_energies_file.name} vs converged VASP PBE, outliers flagged)")


def main():
    parser = argparse.ArgumentParser(
        description="Compare MP and VASP energies from workflow database"
    )
    parser.add_argument(
        '--db',
        type=str,
        default='./mp_relax_workflow.json',
        help="Workflow database file (default: ./mp_relax_workflow.json)"
    )
    parser.add_argument(
        '--mp-energies-file',
        type=str,
        default=None,
        help="Path to mp_vaspdft.json file with MP GGA-PBE energies. "
             "Generated by get_mp_struct.py (mp_cache_structs/mp_vaspdft.json) or "
             "compute_dft_e_hull.py (VASP_JOBS/mp_vaspdft.json). "
             "If not specified, tries both default locations."
    )
    parser.add_argument(
        '--output',
        type=str,
        default='mp_vasp_comparison.json',
        help="Output file for detailed results (default: mp_vasp_comparison.json). "
             "Also generates PNG plots with same prefix."
    )
    parser.add_argument(
        '--no-convergence-check',
        action='store_true',
        help="Skip VASP convergence verification (include all completed structures)"
    )
    parser.add_argument(
        '--outlier-threshold',
        type=float,
        default=0.5,
        help="Absolute energy difference threshold (eV/atom) for outlier detection (default: 0.5)"
    )
    
    args = parser.parse_args()
    
    db_path = Path(args.db).expanduser()
    
    if not db_path.exists():
        print(f"ERROR: Database file not found: {db_path}")
        return 1
    
    # Determine MP energies file path
    if args.mp_energies_file:
        mp_energies_file = Path(args.mp_energies_file).expanduser()
    else:
        # Try default locations
        default_paths = [
            Path('./mp_cache_structs/mp_vaspdft.json'),
            Path('./VASP_JOBS/mp_vaspdft.json')
        ]
        
        mp_energies_file = None
        for path in default_paths:
            if path.exists():
                mp_energies_file = path
                break
        
        if mp_energies_file is None:
            print("ERROR: MP energies file not found!")
            print("\nTried default locations:")
            for path in default_paths:
                print(f"  - {path}")
            print("\nPlease specify --mp-energies-file or generate the file by running:")
            print("  1. get_mp_struct.py (saves to mp_cache_structs/mp_vaspdft.json), or")
            print("  2. compute_dft_e_hull.py (saves to VASP_JOBS/mp_vaspdft.json)")
            return 1
    
    # Load database
    print(f"Loading workflow database: {db_path}")
    db = load_workflow_db(db_path)
    
    total = len(db['structures'])
    completed = sum(1 for s in db['structures'].values() if s['state'] in ('RELAX_DONE', 'RELAX_TMOUT'))
    
    print(f"Total structures: {total}")
    print(f"Completed: {completed}")
    
    if completed == 0:
        print("\nNo completed structures found!")
        return 1
    
    # Get list of completed MP IDs
    completed_mp_ids = [mp_id for mp_id, s in db['structures'].items() 
                        if s['state'] in ('RELAX_DONE', 'RELAX_TMOUT') and s['vasp_energy_per_atom'] is not None]
    
    # Load MP energies from JSON file
    try:
        mp_energies = load_mp_energies_from_json(mp_energies_file)
    except Exception as e:
        print(f"ERROR: Failed to load MP energies: {e}")
        return 1
    
    # Analyze
    print("\nAnalyzing energy differences...")
    check_convergence = not args.no_convergence_check
    if check_convergence:
        print("  (Verifying VASP convergence - use --no-convergence-check to disable)")
    print(f"  (Outlier threshold: |Δ| > {args.outlier_threshold:.2f} eV/atom)")
    results = analyze_energy_differences(
        db, mp_energies, 
        check_convergence=check_convergence,
        outlier_threshold=args.outlier_threshold
    )
    
    if results is None:
        print("ERROR: No valid energy data found")
        return 1
    
    # Print minimal summary
    print_summary(results)
    
    # Save detailed results
    output_prefix = args.output.replace('.json', '')
    save_detailed_comparison(results, args.output, mp_energies_file)
    
    # Generate plots
    print("\nGenerating comparison plots...")
    plot_energy_comparison(results, output_prefix=output_prefix)
    
    print("\n" + "="*70)
    print("Analysis complete!")
    print(f"  JSON results: {args.output}")
    print(f"  Scatter plot: {output_prefix}_scatter.png")
    print(f"  Residual plot: {output_prefix}_residuals.png")
    print(f"  MP energies from: {mp_energies_file}")
    print("="*70 + "\n")
    
    return 0


if __name__ == '__main__':
    import sys
    sys.exit(main())

